<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vibis_ajaxmailsubscription"
 *
 * Auto generated by Extension Builder 2019-01-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Vibis Ajax Mail Subscription',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Vincent Mans',
    'author_email' => 'info@vibis.nl',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
            'tt_address' => '4.0.0-',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
